# Generated by Django 2.2.7 on 2019-11-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191118_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='images',
            new_name='image',
        ),
    ]
